### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by vlgutv22** [devgut/clients-dream-machine#2]
- animate text like obeygiant.com
- have active state change w/blue line
- add  share icons (fb, twitter, instagram) and ios button like: http://www.sololanguage.com/    (will provide icons if needed)
- add contact link to email address animal57co@gmail.com

**Comment by ccsouthard** [comment]
If you need icons in  SVG or PNG-  here is a link to a set that I purchased.

[iOS infinity](https://www.dropbox.com/s/za43bfduwqwexl4/ios-infinity-part1.zip?dl=0)

**Comment by ccsouthard** [comment]
- trigger still there
- need hover on icons lighter or blue
- otherwise done

**Comment by vlgutv22** [comment]
@ccsouthard https://dream-machine.netlify.com/ <<< check pleas) and if everything is fine, give me know and I'll close this issue.

**Comment by ccsouthard** [comment]
fine. let's close

(Sent from a wireless device- please forgive grammar and spelling)
