### ISSUE TITLE
Experiences

### ISSUE THREAD

**Issue by vlgutv22** [devgut/clients-dream-machine#4]
- title should have full blue background
- title should be floated and all resolutions down to ipad two column gallery like [design](https://www.dropbox.com/s/ksi59lpwic5i70b/Screenshot%202017-11-02%2018.32.05.png?dl=0)
- responsive is fine for phone, not enough content shown at regular desktop and ipad landscape.
- how do i add more to gallery?
- if i want to add column in blog/news is this option available?

**Comment by vlgutv22** [comment]
> title should be floated

"Experiences" -title? or...?

**Comment by vlgutv22** [comment]
> how do i add more to gallery?

Via Forestry

**Comment by vlgutv22** [comment]
> if i want to add column in blog/news is this option available?

After Forestry integration

**Comment by ccsouthard** [comment]
Thank you for answering. I think the title should look the same for desktop – but follow the current style for mobile devices. Thoughts?

**Comment by ccsouthard** [comment]
I like your solution. How did you resolve the issue?  The site flows very nicely.
