### ISSUE TITLE
About

### ISSUE THREAD

**Issue by vlgutv22** [devgut/clients-dream-machine#5]
- [header](https://www.dropbox.com/s/spu037mkbqi3xm5/Screenshot%202017-11-02%2018.40.37.png?dl=0) in all cases  should have the same effect as the 1800 pixel design with the slightly dropped down background image  in the text should follow the same look. It was designed in 1800 just so highest resolution would be shown. 
- alpha wave image is [hidden](https://www.dropbox.com/s/iyljxisp4ryeih4/Screenshot%202017-11-02%2018.38.25.png?dl=0)
-  Preserve the integrity of design  please see example
-  [current](https://www.dropbox.com/s/qz1swhqoudlwwfw/Screenshot%202017-11-02%2018.43.15.png?dl=0) and  what [design](https://www.dropbox.com/s/huwur83fa9i4ugb/Screenshot%202017-11-02%2018.44.27.png?dl=0) should look like. 
- parallax bg entrainment image
- footer should also look like [1800](https://www.dropbox.com/s/0yssofcq0bjazlp/Screenshot%202017-11-02%2018.46.51.png?dl=0)
- details are important

**Comment by vlgutv22** [comment]
> current and what design should look like.

If I preserve the integrity of design, It`ll it can be hard readable at smaller devices

**Comment by ccsouthard** [comment]
Maybe split the columns for mobile devices? I'm only commenting on issues that address ambiguity.

**Comment by ccsouthard** [comment]
Looks great. Let's close it.
