### ISSUE TITLE
Q & A

### ISSUE THREAD

**Issue by vlgutv22** [devgut/clients-dream-machine#6]
- header changes like all pages
- keep two col and have text respond i.e. like rem units
- space between sections is slightly off

**Comment by vlgutv22** [comment]
> keep two col and have text respond i.e. like rem units

If use rem for current case, It`ll very small and hard readable

**Comment by ccsouthard** [comment]
Do you have any ideas on how we can keep legibility but similar dimensions?

**Comment by vlgutv22** [comment]
@ccsouthard Only adaptive helps for readability.  (change block size, order, etc). Save template for 1800 in 768 - unreal...

**Comment by ccsouthard** [comment]
I'm not sure I understand. unreal?

(Sent from a wireless device- please forgive grammar and spelling)

**Comment by vlgutv22** [comment]
@ccsouthard I mean that:
if you want take 1800 design and do same for 768, same blocks position and etc... - sure that's possible, but page'll be very tiny... And on "Unreal" I mean that It'll have not readable look

**Comment by ccsouthard** [comment]
ok. Let's see if we can get a close to the 1400px  design as possible. I'm
still waiting for a mockup from the designer and I hate to put anything on
hold. Let me know what issues are best to resolve first and then we can go
back to this one. I will make time to work through the weekend.

 I appreciate your dedication.

(Sent from a wireless device- please forgive grammar and spelling)

**Comment by ccsouthard** [comment]
Also, I currently have an account w/netlify (2 years).  I used to use
roots.cx.
https://github.com/ccsouthard/chazsouthard.com

Unfortunately, this needs updating as well – it is a JS based SSG and has
been abandoned due to language deprecation.

 I will attend to all these issues tonight. I have to use an app
optimization tool which is running out in a day or so and need to gather
all the analytics so I'm a little pressured with time.




(Sent from a wireless device- please forgive grammar and spelling)

**Comment by vlgutv22** [comment]
@ccsouthard Ok. Don't worry! I have what I might to do.
But will be better if designer have done 768 template, It will be perfect. Because from 1800 to 1400 it is responsive, and then for device smaller we should use adaptive approach. But don't worry, when I will closer to resolve this issue, I'll do before that a proposal how it will be look.

**Comment by ccsouthard** [comment]
Awesome. I hate waiting for the designer. If I don't hear back and you have
a good solution – I will follow your lead. Thank you again.

(Sent from a wireless device- please forgive grammar and spelling)

**Comment by vlgutv22** [comment]
@ccsouthard Designers are special guys))) But be calm, everything is fine)
