### ISSUE TITLE
Original Dreamachine

### ISSUE THREAD

**Issue by vlgutv22** [devgut/clients-dream-machine#7]
- header changes like all pages
- keep left/right margin spacing like other pages for design. It should adapt. 
- too much space i.e. [header](https://www.dropbox.com/s/l4hk57u4vvyvebq/Screenshot%202017-11-02%2018.54.06.png?dl=0)
- parallax big images
- line [height](https://www.dropbox.com/s/jx3v4omnycal7bk/Screenshot%202017-11-02%2018.59.01.png?dl=0) needs to be responsive for [readability](https://www.dropbox.com/s/5wkorxd6i5qw2oz/Screenshot%202017-11-02%2018.59.41.png?dl=0).

**Comment by ccsouthard** [comment]
Looks great. Spacing and line height are perfect.
